backend:
  name: github
  repo: Norman521/my-app # your repo
  branch: main
  base_url: https://my-app-ivory-rho-95.vercel.app # <-- must match EXACT domain
  auth_endpoint: /api/auth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Caption", name: "caption", widget: "text", required: false }
