media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "gallery"
    folder: "content/gallery" # ← matches code above
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Caption", name: "caption", widget: "text", required: false }
